import { ElementTemplate } from "@/types";

export const ELEMENT_TEMPLATES: Record<string, ElementTemplate> = {
  navbar: {
    type: "navbar",
    label: "Navigation Bar",
    category: "navigation",
    icon: "📌",
    description: "Top navigation with brand, links, and CTA button",
    defaultProps: {
      brand: "AgentForge",
      links: ["Home", "Features", "Pricing", "Docs"],
      btnText: "Sign In",
      bg: "#ffffff",
      color: "#0f172a",
      accent: "#8b5cf6",
      sticky: true,
    },
  },
  hero: {
    type: "hero",
    label: "Hero Section",
    category: "content",
    icon: "🖼️",
    description: "Large headline with subtitle, CTA button and optional image",
    defaultProps: {
      title: "Welcome to AgentForge",
      subtitle:
        "Build, certify, and deploy AI assets across your organization.",
      btnText: "Get Started",
      btnColor: "#8b5cf6",
      bg: "linear-gradient(135deg, #1e1b4b, #312e81)",
      textColor: "#ffffff",
      align: "left",
      showImage: true,
      imageEmoji: "🤖",
    },
  },
  stats: {
    type: "stats",
    label: "Stats Row",
    category: "content",
    icon: "📈",
    description: "Horizontal row of key metrics",
    defaultProps: {
      items: [
        { value: "847+", label: "Assets", color: "#8b5cf6" },
        { value: "12", label: "Countries", color: "#3b82f6" },
        { value: "99.7%", label: "Uptime", color: "#22c55e" },
        { value: "5.2K", label: "Users", color: "#f59e0b" },
      ],
      bg: "#ffffff",
    },
  },
  cards: {
    type: "cards",
    label: "Card Grid",
    category: "content",
    icon: "🃏",
    description: "Grid of feature or info cards with icons",
    defaultProps: {
      columns: 3,
      items: [
        {
          icon: "🤖",
          title: "AI Agents",
          desc: "Deploy intelligent agents across your org",
          color: "#a855f7",
        },
        {
          icon: "📊",
          title: "Analytics",
          desc: "Real-time dashboards and cost tracking",
          color: "#3b82f6",
        },
        {
          icon: "🔐",
          title: "Governance",
          desc: "Enterprise-grade RBAC and compliance",
          color: "#22c55e",
        },
      ],
    },
  },
  features: {
    type: "features",
    label: "Feature List",
    category: "content",
    icon: "⚡",
    description: "Two-column feature grid with icons",
    defaultProps: {
      title: "Everything you need",
      subtitle: "Built for enterprise teams at scale",
      items: [
        {
          icon: "⚡",
          title: "Lightning Fast",
          desc: "Sub-second response times across all operations",
        },
        {
          icon: "🔄",
          title: "Auto Scaling",
          desc: "Scales from 10 to 10,000 users seamlessly",
        },
        {
          icon: "🛡️",
          title: "Enterprise Security",
          desc: "SOC 2, GDPR, and HIPAA compliant out of the box",
        },
        {
          icon: "🌐",
          title: "Multi-Region",
          desc: "Deploy in US, EU, and APAC with data residency",
        },
      ],
      bg: "#ffffff",
    },
  },
  form: {
    type: "form",
    label: "Form Section",
    category: "form",
    icon: "📝",
    description: "Contact or input form with configurable fields",
    defaultProps: {
      title: "Get in Touch",
      fields: [
        { label: "Full Name", type: "text", placeholder: "John Doe" },
        {
          label: "Work Email",
          type: "email",
          placeholder: "john@company.com",
        },
        { label: "Company", type: "text", placeholder: "Acme Inc." },
        {
          label: "Message",
          type: "textarea",
          placeholder: "Tell us about your needs...",
        },
      ],
      btnText: "Submit",
      btnColor: "#8b5cf6",
      bg: "#f8f9fb",
    },
  },
  cta: {
    type: "cta",
    label: "Call to Action",
    category: "content",
    icon: "🎯",
    description: "Centered CTA banner with headline and button",
    defaultProps: {
      title: "Ready to transform your AI operations?",
      subtitle: "Join 500+ enterprise teams already using AgentForge.",
      btnText: "Start Free Trial",
      btnColor: "#8b5cf6",
      bg: "linear-gradient(135deg, #4c1d95, #7c3aed)",
      textColor: "#ffffff",
    },
  },
  testimonial: {
    type: "testimonial",
    label: "Testimonial",
    category: "content",
    icon: "💬",
    description: "Customer quote with author and rating",
    defaultProps: {
      quote:
        "AgentForge reduced our AI deployment time from weeks to hours. The SDLC pipeline gives our risk team full confidence.",
      author: "Sarah Chen",
      role: "Head of AI, Advisory",
      avatar: "SC",
      rating: 5,
      bg: "#ffffff",
    },
  },
  pricing: {
    type: "pricing",
    label: "Pricing Cards",
    category: "content",
    icon: "💳",
    description: "Multi-tier pricing comparison cards",
    defaultProps: {
      items: [
        {
          name: "Starter",
          price: "$0",
          period: "/month",
          desc: "For individuals exploring AI",
          features: ["5 AI agents", "1,000 queries/mo", "Community support"],
          color: "#64748b",
          featured: false,
        },
        {
          name: "Professional",
          price: "$49",
          period: "/month",
          desc: "For growing teams",
          features: [
            "50 AI agents",
            "50,000 queries/mo",
            "Priority support",
            "Custom models",
          ],
          color: "#8b5cf6",
          featured: true,
        },
        {
          name: "Enterprise",
          price: "Custom",
          period: "",
          desc: "For large organizations",
          features: [
            "Unlimited agents",
            "Unlimited queries",
            "Dedicated CSM",
            "SLA & BAA",
            "SSO & SCIM",
          ],
          color: "#0f172a",
          featured: false,
        },
      ],
    },
  },
  text: {
    type: "text",
    label: "Text Block",
    category: "content",
    icon: "📄",
    description: "Rich text paragraph",
    defaultProps: {
      content:
        "This is a paragraph of text. You can edit this to say anything you want.",
      size: 15,
      color: "#475569",
      align: "left",
      bg: "transparent",
      maxWidth: 700,
      padding: 24,
    },
  },
  divider: {
    type: "divider",
    label: "Divider",
    category: "layout",
    icon: "➖",
    description: "Horizontal line separator",
    defaultProps: {
      style: "solid",
      color: "#e2e8f0",
      spacing: 32,
    },
  },
  image: {
    type: "image",
    label: "Image Placeholder",
    category: "media",
    icon: "📷",
    description: "Image block with placeholder",
    defaultProps: {
      width: "100%",
      height: 300,
      bg: "#f1f5f9",
      label: "Image Placeholder",
      borderRadius: 16,
    },
  },
  footer: {
    type: "footer",
    label: "Footer",
    category: "navigation",
    icon: "🔻",
    description: "Page footer with columns and copyright",
    defaultProps: {
      brand: "AgentForge",
      tagline: "Building the future of AI operations.",
      columns: [
        {
          title: "Product",
          links: ["Features", "Pricing", "Changelog", "Roadmap"],
        },
        {
          title: "Resources",
          links: ["Docs", "API Reference", "Templates", "Blog"],
        },
        {
          title: "Company",
          links: ["About", "Careers", "Contact", "Legal"],
        },
      ],
      copyright: "© 2026 AgentForge. All rights reserved.",
      bg: "#0f172a",
      color: "#94a3b8",
    },
  },
};

export const TEMPLATE_CATEGORIES = [
  { id: "navigation", label: "Navigation", icon: "📌" },
  { id: "content", label: "Content", icon: "📄" },
  { id: "form", label: "Forms", icon: "📝" },
  { id: "layout", label: "Layout", icon: "📐" },
  { id: "media", label: "Media", icon: "📷" },
];
